# Generated by Django 5.1.7 on 2025-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
