# Generated by Django 5.1.7 on 2025-03-19 08:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
